[versions]
# plugins
kotlin = "2.0.0"
changelog = "2.2.0"
intelliJPlatform = "2.0.0"
qodana = "2024.1.5"
kotlinxSerialization = "1.7.1"
okhttp = "4.12.0"
markdown = "0.7.3"

[libraries]
kotlinxSerialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerialization" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
markdown = { module = "org.jetbrains:markdown-jvm", version.ref = "markdown" }

[plugins]
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
qodana = { id = "org.jetbrains.qodana", version.ref = "qodana" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
intelliJPlatform = { id = "org.jetbrains.intellij.platform", version.ref = "intelliJPlatform" }